### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by milahu** [LanikSJ/dfimage#173]
dfimage looks broken

workaround: use https://github.com/mrhavens/Dedockify

similar to #35 

```
imageName=xxx/yyy:latest
docker pull $imageName
docker images # -> get image ID
imageId=zzzzzzzzzz

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/laniksj/dfimage $imageId
Traceback (most recent call last):
  File "/root/entrypoint.py", line 56, in <module>
    __main__ = MainObj()
  File "/root/entrypoint.py", line 16, in __init__
    self._get_image(argv[-1])
  File "/root/entrypoint.py", line 32, in _get_image
    raise ImageNotFound("Image {} not found\n".format(repo_tag))
__main__.ImageNotFound: Image zzzzzzzzzz not found

# compare: dedockify
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock mrhavens/dedockify $imageId
# -> ok. dockerfile is printed to stdout

# compare: dockerfile-from-image
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock centurylink/dockerfile-from-image $imageName
/usr/lib/ruby/gems/2.2.0/gems/docker-api-1.24.1/lib/docker/connection.rb:42:in `rescue in request': 400 Bad Request: malformed Host header (Docker::Error::ClientError)
```

**Comment by LanikSJ** [comment]
Have you read the [README.md](https://github.com/LanikSJ/dfimage/blob/master/README.md)? This project doesn't use `imageId` any longer.  It's nice that someone copied my project almost verbatim and is using my old logic without any attribution. 🙁

**Comment by milahu** [comment]
pardon my brevity. i tried multiple combinations, and none works

> This project doesn't use `imageId` any longer.

i also tried `$imageName` but i get the same error

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/laniksj/dfimage ruby:latest 
Traceback (most recent call last):
  File "/root/entrypoint.py", line 56, in <module>
    __main__ = MainObj()
  File "/root/entrypoint.py", line 16, in __init__
    self._get_image(argv[-1])
  File "/root/entrypoint.py", line 32, in _get_image
    raise ImageNotFound("Image {} not found\n".format(repo_tag))
__main__.ImageNotFound: Image ruby:latest not found
```

`ghcr.io/laniksj/dfimage` &rarr; `dfimage`

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock dfimage ruby:latest
Unable to find image 'dfimage:latest' locally
docker: Error response from daemon: pull access denied for dfimage, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

docker pull dfimage
Using default tag: latest
Error response from daemon: pull access denied for dfimage, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by LanikSJ** [comment]
> ```
> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/laniksj/dfimage ruby:latest 
> Traceback (most recent call last):
>   File "/root/entrypoint.py", line 56, in <module>
>     __main__ = MainObj()
>   File "/root/entrypoint.py", line 16, in __init__
>     self._get_image(argv[-1])
>   File "/root/entrypoint.py", line 32, in _get_image
>     raise ImageNotFound("Image {} not found\n".format(repo_tag))
> __main__.ImageNotFound: Image ruby:latest not found
You'll need to have done a `docker pull` on `ruby:latest` before running the above command.
```
docker pull ruby:latest
```

> 
> `ghcr.io/laniksj/dfimage` → `dfimage`
> 
> ```
> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock dfimage ruby:latest
> Unable to find image 'dfimage:latest' locally
> docker: Error response from daemon: pull access denied for dfimage, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
That won't work since the docker hub image isn't hosted on docker.io namespace:
```
docker pull laniksj/dfimage
```
if you want the image that's no longer being updated and doesn't have the latest changes.

> docker pull dfimage
> Using default tag: latest
> Error response from daemon: pull access denied for dfimage, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

See above.

**Comment by milahu** [comment]
thanks for explaining

rtfm:

> Note that the script only works against images that exist in your local image repository (the stuff you see when you type docker images). If you want to generate a Dockerfile for an image that doesn't exist in your local repo you'll first need to docker pull it.

can we catch `__main__.ImageNotFound: Image ruby:latest not found`
and print something like "please run: docker pull ruby:latest"?

the uncaught exception makes it look like a bug

**Comment by LanikSJ** [comment]
> can we catch `__main__.ImageNotFound: Image ruby:latest not found` and print something like "please run: docker pull ruby:latest"?
> 
> the uncaught exception makes it look like a bug

That's a good idea I'll look into adding that to the project.
