### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by testwill** [LanikSJ/dfimage#186]
### Description

#  dfimage  192.168.1.94:443/library/xmrig/xmrig:v1
Traceback (most recent call last):
  File "/root/entrypoint.py", line 56, in <module>
    __main__ = MainObj()
  File "/root/entrypoint.py", line 16, in __init__
    self._get_image(argv[-1])
  File "/root/entrypoint.py", line 29, in _get_image
    if repo_tag in i['RepoTags']:
TypeError: argument of type 'NoneType' is not iterable
root@jack-virtual-machine:/home/jack/test/ttttt# echo dfimage
dfimage
root@jack-virtual-machine:/home/jack/test/ttttt# echo $dfimage

root@jack-virtual-machine:/home/jack/test/ttttt# docker inspect 192.168.1.94:443/library/xmrig/xmrig:v1
[
    {
        "Id": "sha256:2a06e9574854723b606ef03dda327158edd3525c8454661712db49a5548bc0d0",
        "RepoTags": [
            "192.168.1.94:443/library/xmrig/xmrig:v1"
        ],

### Docker Config

```bash
1. Open Docker Desktop
2. Docker Desktop > About
```

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by LanikSJ** [comment]
`NoneType` means it couldn't find the image name and or tag.  Make sure you pull the image first before running that command.  Also your `dfimage` command is aliased to `docker inspect` vs what the directions in the [README.md](https://github.com/LanikSJ/dfimage/blob/master/README.md).
