### ISSUE TITLE
🐛 [BUG] - RUN prefix on each command if multi stage build is used

### ISSUE THREAD

**Issue by sino1641** [LanikSJ/dfimage#251]
### Description

RUN prefix on each command if multi stage build is used
<img width="777" alt="Snipaste_2024-05-04_14-25-08" src="https://github.com/LanikSJ/dfimage/assets/13870295/812ca7fb-793f-4dd3-8195-5560bdb78b62">
Also, it seems #155 still exists here.

### Docker Config

```bash
Client:
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.20.12
 Git commit:        4debf41
 Built:             Mon Feb 12 00:00:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.20.12
  Git commit:       f417435
  Built:            Mon Feb 12 00:00:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
```

### Reproduction steps

```bash
docker run -v /var/run/docker.sock:/var/run/docker.sock --rm ghcr.io/laniksj/dfimage portainer/portainer-ce:latest
```

### OS

Linux

**Comment by LanikSJ** [comment]
I think it's coming from here:
https://github.com/LanikSJ/dfimage/blob/20ca8a13df3f421257b039d73c8fc0a7e8d71f31/entrypoint.py#L79-L82

I'll have to try some stuff as I'm not that good with Python unfortunately.
